# Generated by Django 3.0.4 on 2020-03-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='No image available...', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='No link provided...', max_length=300),
        ),
    ]
