# Generated by Django 3.0.4 on 2020-03-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='No link provided...', max_length=300),
        ),
    ]
