# Generated by Django 3.0.4 on 2020-03-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200309_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='playable',
            field=models.BooleanField(default=False),
        ),
    ]
