# Generated by Django 3.0.4 on 2020-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_playable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='playable',
        ),
        migrations.AddField(
            model_name='project',
            name='play_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
